## Connect to your pihole running on an external device (raspberry pi)

[backends]
  [backends.pihole]
    [backends.pihole.servers]
      [backends.pihole.servers.server-pihole-ext]
        url = "http://192.168.1.200:80"

## Connect to your unifi controller running on an external device (raspberry pi)

  [backends.unifi]
    [backends.unifi.servers]
      [backends.unifi.servers.server-unifi-ext]
        url = "https://192.168.1.200:8443"


[frontends]
  [frontends.pihole]
    backend = "pihole"
    passHostHeader = true
#      [frontends.pihole.auth.basic]
#        usersFile = "/shared/.htpasswd"
      [frontends.pihole.auth]
        headerField = "X-WebAuth-User"
        [frontends.pihole.auth.forward]
          address = "http://oauth:4181"
          trustForwardHeader = true
          authResponseHeaders = ["X-Forwarded-User"]
      [frontends.pihole.routes]
        [frontends.pihole.routes.route-pihole-ext]
          rule = "Host:pihole.domain.net;AddPrefix:/admin"
      [frontends.pihole.headers]
        SSLRedirect = true
        SSLHost = "pihole.domain.net"
        SSLForceHost = true
        STSSeconds = 315360000
        STSIncludeSubdomains = true
        STSPreload = true
        forceSTSHeader = true
        frameDeny = true
        contentTypeNosniff = true
        browserXSSFilter = true
        customResponseHeaders = "X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex"

  [frontends.unifi]
    backend = "unifi"
    passHostHeader = true
#      [frontends.pihole.auth.basic]
#        usersFile = "/shared/.htpasswd"
      [frontends.unifi.auth]
        headerField = "X-WebAuth-User"
        [frontends.unifi.auth.forward]
          address = "http://oauth:4181"
          trustForwardHeader = true
          authResponseHeaders = ["X-Forwarded-User"]
      [frontends.unifi.routes]
        [frontends.unifi.routes.route-unifi-ext]
          rule = "Host:unifi.domain.net"
      [frontends.unifi.headers]
        SSLRedirect = true
        SSLHost = "unifi.domain.net"
        SSLForceHost = true
        STSSeconds = 315360000
        STSIncludeSubdomains = true
        STSPreload = true
        forceSTSHeader = true
        frameDeny = true
        contentTypeNosniff = true
        browserXSSFilter = true
        customResponseHeaders = "X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex"
